In [9]:
import numpy as np
a = np.arange(10)
b = np.arange(10)
print(b)
print(a)
print(a+b)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[ 0  2  4  6  8 10 12 14 16 18]


También se pueden utilizar para ser comparador con multiindex


In [22]:
a = np.arange(5)
print(a[a >= 2])  #En este caso lo que está realizando es filtrarlo para que solo salgan por pantallan los que sean mayores o iguales a 2

#También puede utilizarlo con el .mean y que compara 
print(a[a <= a.mean()]) 

#También se puede utilizar para poder craer matrices 

x = np.random.randint(100, size=(5,5))    #En este caso se está creando una matriz de 5x5 con números aleatorios entre 0 y 100
print(x)
x > 30



[2 3 4]
[0 1 2]
[[45 68 38 56 60]
 [15 27 50 14 85]
 [38 68 32 11 96]
 [32  1  4 72 81]
 [13 39 30 96 70]]


array([[ True,  True,  True,  True,  True],
       [False, False,  True, False,  True],
       [ True,  True,  True, False,  True],
       [ True, False, False,  True,  True],
       [False,  True, False,  True,  True]])

También pueden ser combinados con | o y 